### ISSUE TITLE
 Content-Length mismatch

### ISSUE THREAD

**Issue by jomonkj** [hiqdev/asset-packagist#104]
while composer update/install
```ssh
[Composer\Downloader\TransportException]                                   
  Content-Length mismatch, received 81664 bytes out of the expected 3936993  
```

![DeepinScreenshot_20191025104749](https://user-images.githubusercontent.com/11212888/67545027-3c53a780-f715-11e9-8901-99aca8dbf6c0.png)

**Comment by eiriksm** [comment]
Seeing this too.

As a workaround, if you are not actually updating the packages you are requiring from asset-packagist, you can just remove the repo from your `composer.json` while you are updating.

**Comment by jomonkj** [comment]
it works now
thanks @hiqsol

**Comment by eiriksm** [comment]
Seeing this error again today in our build systems. Same problem? :)

**Comment by kdo70** [comment]
Today when updating we get this error.

**Comment by koddistortion** [comment]
I am experiencing the same problem today.

**Comment by Jelle-S** [comment]
Same problem here

**Comment by mice-tm** [comment]
Just the same

**Comment by rhabegger** [comment]
Same problem here ;(

**Comment by kamarton** [comment]
This link contains an incomplete JSON:

https://asset-packagist.org/p/provider-latest/b5908562564adbe06c4e702fd75e7faa8f6d9e7a08a2f99b551bfdcb1300f79d.json

**Comment by rhabegger** [comment]
> This link contains an incomplete JSON:
> 
> https://asset-packagist.org/p/provider-latest/b5908562564adbe06c4e702fd75e7faa8f6d9e7a08a2f99b551bfdcb1300f79d.json

I was just about to post the same thing ...

**Comment by abdalovalex** [comment]
Just the same

**Comment by demonking** [comment]
see #105 someone is working on this problem

**Comment by SilverFire** [comment]
Fixed

**Comment by My6UoT9** [comment]
What was the reason? Its not going to happen again next week right?

**Comment by SilverFire** [comment]
> What was the reason?

Insufficient disk space.


> Its not going to happen again next week right?

We have purchased additional 60GB of storage, which will be enough for at least 1 year of the DB growth.

**Comment by webmayak** [comment]
the problem still persists.. 😢
![image](https://user-images.githubusercontent.com/642519/67736523-b2c51200-fa53-11e9-9eaf-12d54e887fb2.png)
```
{
    "require": {
        "yiisoft/yii2": "~2.0.0",
        "paulzi/yii2-nested-sets": "^1.1",
        "notamedia/yii2-sentry": "^1.4"
    },
    "require-dev": {
        "codeception/base": "~2.3.0",
        "codeception/verify": "~0.4.0",
        "codeception/specify": "~0.4.6",
        "symfony/browser-kit": ">=2.7 <=4.2.4"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ],
    "autoload": {
        "psr-4": {"app\\": ""}
    }
}
```

**Comment by SilverFire** [comment]
The additional storage was purchased but has not been mounted yet.
The reboot is scheduled on this evening

**Comment by SilverFire** [comment]
Meanwhile, the problem is fixed manually again. Sorry, guys, I hope this evening reboot will be the last outage.

**Comment by rhabegger** [comment]
Hi guy, is the new disk mounted ?
I still have content-length-mismatch errors this morning ...

**Comment by kdo70** [comment]
Today when updating we get this error. (2)

**Comment by hiqsol** [comment]
Sorry! Should be ok now
