### ISSUE TITLE
composer update is failing

### ISSUE THREAD

**Issue by mably** [hiqdev/asset-packagist#181]
```
Root composer.json requires npm-asset/cropper ^4.1, found npm-asset/cropper[4.1.0] in the lock file but not in remote repositories, make sure you avoid updating this package to keep the one from the lock file.
```

**Comment by Harkonn** [comment]
https://asset-packagist.org/package/npm-asset/dropzone works now. The 500 errors are gone, too.. The Website says "Last updated: 10 minutes ago"
Still no Commit SHAs, but composer does download 5.9.3 now.

<img width="1062" height="545" alt="Image" src="https://github.com/user-attachments/assets/1c8cebd8-979a-438f-b89f-f7ff632ddc8d" />

**Comment by nadar** [comment]
not sure its related, but doing composer update suddenly gives us

<img width="2188" height="225" alt="Image" src="https://github.com/user-attachments/assets/977f794d-ebed-455f-8e6e-0afe658710af" />

**Comment by damienmckenna** [comment]
FWIW I used [normanlolx](https://github.com/normanlolx)'s example code to add individual package definitions for the bower-asset and npm-asset packages listed on projects and it worked fine, so thank you normanlolx for the suggestion. While this may not be the cleanest way of managing the composer.json file, it works as a temporary solution.

**Comment by jbboisseau** [comment]
Still very unstable on my side: I've just had a complete update succeeding... and then it failed again few moments later (for the same packages).

**Comment by SilverFire** [comment]
In case this shit hapens again, here is how I fixed it:


1.  Build `providers.json` for each `bower-asset` and `npm-asset` separately:
```python
import os
import json
import hashlib

def calculate_sha256(file_path):
    """Calculates SHA256 hash in chunks to be memory efficient."""
    sha256_hash = hashlib.sha256()
    try:
        with open(file_path, "rb") as f:
            # Read in 4KB chunks
            for byte_block in iter(lambda: f.read(4096), b""):
                sha256_hash.update(byte_block)
        return sha256_hash.hexdigest()
    except Exception as e:
        print(f"Error hashing {file_path}: {e}")
        return None

def build_provider_json():
    providers = {}
    base_dir = "web/p/npm-asset" # or bower-asset
    target_filename = "latest.json"

    print(f"Scanning and hashing files in: {os.path.abspath(base_dir)}")

    for root, dirs, files in os.walk(base_dir):
        if target_filename in files:
            full_path = os.path.join(root, target_filename)

            # Clean path (e.g., ./npm-asset/es-info -> npm-asset/es-info)
            provider_path = os.path.relpath(root, base_dir)

            # Calculate hash
            file_hash = calculate_sha256(full_path)

            if file_hash:
                providers[provider_path] = {"sha256": file_hash}

                # OPTIONAL: Save the .sha256 file to disk like your original command did
                with open(f"{full_path}.sha256", "w") as f:
                    f.write(file_hash)

    # Wrap in final structure
    output = {"providers": providers}

    with open("providers.json", "w") as f:
        json.dump(output, f, indent=2)

    print(f"Success! Generated providers.json with {len(providers)} entries.")

if __name__ == "__main__":
    build_provider_json()
```

2. Merge them
```bash
jq -s '.[0].providers * .[1].providers | {providers: .}' providers.json_bower providers.json_npm > providers.json
```

3. Substitute broken `latest.json`
```bash
mv providers.json web/p/provider-latest/latest.json
```

4. Update any package, so `latest.json` will be used as a source to build other files

**Comment by Jane-Irwin-UM** [comment]
Thank you so much @SilverFire for giving up your holiday time to solve this issue. We appreciate you!

**Comment by dipakmdhrm** [comment]
Thank you @SilverFire !!

**Comment by Ilya-Ruk** [comment]
I have a new problem :(

<img width="1103" height="639" alt="Image" src="https://github.com/user-attachments/assets/36bb249a-dc8a-4e0c-8b94-6244bbf4c0fa" />

**Comment by FlorentTorregrosa** [comment]
Hi,

Thanks @SilverFire for your work on this issue.

Is there some kind of data rebuild/propagation to wait for? I am still having the issue:

```
Problem 1
    - Root composer.json requires npm-asset/bootstrap 5.3.8 (exact version match: 5.3.8 or 5.3.8.0), found npm-asset/bootstrap[5.3.8] in the lock file but not in remote repositories, make sure you avoid updating this package to keep the one from the lock file.
  Problem 2
    - Root composer.json requires npm-asset/bootstrap-icons, it could not be found in any version, there may be a typo in the package name.
  Problem 3
    - Root composer.json requires npm-asset/fortawesome--fontawesome-free 7.1.0 (exact version match: 7.1.0 or 7.1.0.0), found npm-asset/fortawesome--fontawesome-free[7.1.0] in the lock file but not in remote repositories, make sure you avoid updating this package to keep the one from the lock file.
```

**Comment by Ilya-Ruk** [comment]
>Does the package fetch from website solve the problem?

No

**Comment by Jane-Irwin-UM** [comment]
Yes, unfortunately we're also seeing the same issue again.

**Comment by FlorentTorregrosa** [comment]
Good for me now, thanks @SilverFire !

**Comment by SilverFire** [comment]
@romanchuykov-ai Does the package fetch from website solve the problem for you?

**Comment by romanchuykov-ai** [comment]
> [@romanchuykov-ai](https://github.com/romanchuykov-ai) Does the package fetch from website solve the problem for you?

I have a new error now.

<img width="1262" height="127" alt="Image" src="https://github.com/user-attachments/assets/88185b7c-5aff-4462-be2c-f403792c1e5b" />

<img width="1347" height="155" alt="Image" src="https://github.com/user-attachments/assets/248b5587-3b89-4fdc-8e9b-05db0e8bcc94" />

**Comment by vtestagrossa** [comment]
> > [@romanchuykov-ai](https://github.com/romanchuykov-ai) Does the package fetch from website solve the problem for you?
> 
> I have a new error now.
> 
> <img alt="Image" width="1262" height="127" src="https://private-user-images.githubusercontent.com/247616830/530080498-88185b7c-5aff-4462-be2c-f403792c1e5b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjY2MDc2MzIsIm5iZiI6MTc2NjYwNzMzMiwicGF0aCI6Ii8yNDc2MTY4MzAvNTMwMDgwNDk4LTg4MTg1YjdjLTVhZmYtNDQ2Mi1iZTJjLWY0MDM3OTJjMWU1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIyNFQyMDE1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjdhNzZhZjgxZmIyOWFlMGFkNTZmZjlmMDNkN2RlNzFiYTJmMjkxY2JkYWQ3YzU2MTE4OTBkMzY4NDgwMmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2KfQ6ADeaQLqnJlSdpDz21aXLrWddO6f0hZFBpISI2c"> <img alt="Image" width="1347" height="155" src="https://private-user-images.githubusercontent.com/247616830/530080530-248b5587-3b89-4fdc-8e9b-05db0e8bcc94.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjY2MDc2MzIsIm5iZiI6MTc2NjYwNzMzMiwicGF0aCI6Ii8yNDc2MTY4MzAvNTMwMDgwNTMwLTI0OGI1NTg3LTNiODktNGZkYy04ZTliLTA1ZGIwZThiY2M5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIyNFQyMDE1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTM1NzAwN2JmN2RhMTE2M2Y3M2VmYjZiMGRiZDBjZjMyYmFmNjVhNjIwOWQ1YTJkNTIyNTc0NTcwYjI2YzlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-RWnYZFAu-QqewHP9hpLTNvXUjUv10E2th5WJtt_Gtc">

Everything was working yesterday, but now I'm having a similar issue with json-buffer:
> Loading composer repositories with package information 
> 17.07
> 17.09 In CurlDownloader.php line 668: 
> 17.09 
> 17.09 The "https://cdn.asset-packagist.org/p/npm-asset/json-buffer/02b296c7464f14
> 17.09 1af9abf07e75510ab8523cb59994757af0da1b1abeb6dc931e.json" file could not be
> 17.09 downloaded (HTTP/2 404 )

**Comment by mortona42** [comment]
Also getting errors with cdn json files: https://cdn.asset-packagist.org/p/npm-asset/call-limit/8347d5a30babc3552a2bb4bb8928c37a2dcc5998098bd11126ebc3e4bdbbca7b.json

One that was broken started working later, so I assume they are just taking longer to propagate.

Removing the npm-asset repository definition from composer.json temporarily lets you install and update other things.

Thanks for all your contributions @SilverFire. I've been using this for years without any other issues.

**Comment by ProkopenkoRoman** [comment]
Errors like "The https://cdn.asset-packagist.org/p <...> file could not be downloaded (HTTP/2 404 )" do not observed now.
Thanks you @SilverFire for your work!

**Comment by vtestagrossa** [comment]
Everything is working again for me today.

**Comment by themikem** [comment]
Now seeing a new error - maybe something with the CDN...?
`The contents of https://asset-packagist.org/p/npm-asset/listr-silent-renderer/8a76f6a423ec4c6801f6321379dba83dbdc2b8ef6611f26683edaf84fc2822e6.json do not match its signature. This could indicate a man -in-the-middle attack or e.g. antivirus software corrupting files. Try running composer again and report this if you think it is a mistake.`

**Comment by Amadeco** [comment]
> "repositories": [
>     {
>         "type": "composer",
>         "url": "https://pullzone.asset-packagist.org"
>     }
> ]

Thank you @SilverFire !

Solved the issue for now with your advice ;-)

**Comment by rkcreation** [comment]
@SilverFire it seems to be the same problem here #183

**Comment by ligams** [comment]
Fetched some packets in UI, was OK after several minutes ... dunno if it is related

**Comment by crazyxoma** [comment]
The same problem(

**Comment by fericsangabor** [comment]
Loading composer repositories with package information

Updating dependencies
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Root composer.json requires npm-asset/todesktop--client-electron-types, it could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Root composer.json requires npm-asset/todesktop--client-electron-updater-types, it could not be found in any version, there may be a typo in the package name.
  Problem 3
    - Root composer.json requires npm-asset/todesktop--client-core, it could not be found in any version, there may be a typo in the package name.
  Problem 4
    - Root composer.json requires npm-asset/moment, it could not be found in any version, there may be a typo in the package name.
  Problem 5
    - Root composer.json requires npm-asset/startbootstrap-sb-admin-2, it could not be found in any version, there may be a typo in the package name.
  Problem 6
    - Root composer.json requires npm-asset/jstree, it could not be found in any version, there may be a typo in the package name.
  Problem 7
    - Root composer.json requires npm-asset/jquery-ui-touch-punch, it could not be found in any version, there may be a typo in the package name.
  Problem 8
    - Root composer.json requires npm-asset/onscan.js, it could not be found in any version, there may be a typo in the package name.
  Problem 9
    - Root composer.json requires bower-asset/toastr, it could not be found in any version, there may be a typo in the package name.

..etc

**Comment by nadar** [comment]
same :-/ maybe needs time to recover?

> Your requirements could not be resolved to an installable set of packages.
> 
>  Problem 1
>   - Root composer.json requires yiisoft/yii2 ^2.0.47 -> satisfiable by yiisoft/yii2[2.0.52, 2.0.53, 2.0.54].
>    - yiisoft/yii2[2.0.52, ..., 2.0.54] require bower-asset/jquery 3.7.*@stable | 3.6.*@stable | 3.5.*@stable | 3.4.*@stable | > > 3.3.*@stable | 3.2.*@stable | 3.1.*@stable | 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> found bower-asset/jquery[3.7.1] in the lock file but not in remote repositories, make sure you avoid updating this package to keep the one from the lock file.

**Comment by lshaf** [comment]
oh dang, I can't work on my project without this....

**Comment by kabachello** [comment]
Same here. The issue is back since yesterday evening. This workaround works for me, but it is a pain...

> temporary workaround: because the "latest.json" url work, but the hash url not
> 
> ```
> 	"repositories": [
> ...
> 		{
> 			"type": "composer",
> 			"url": "https://cdn.asset-packagist.org/p/npm-asset/bootstrap/latest.json",
> 			"only": [
> 				"npm-asset/bootstrap"
> 			]
> 		},
> 		{
> 			"type": "composer",
> 			"url": "https://cdn.asset-packagist.org/p/npm-asset/chart.js/latest.json",
> 			"only": [
> 				"npm-asset/chart.js"
> 			]
> 		},
> 		{
> 			"type": "composer",
> 			"url": "https://cdn.asset-packagist.org/p/npm-asset/jquery/latest.json",
> 			"only": [
> 				"npm-asset/jquery"
> 			]
> 		},
>     ]
> ```

**Comment by SilverFire** [comment]
Found and fixed a race condition https://github.com/hiqdev/asset-packagist/commit/18f34cc2458819c953c8f328530f1826f4e0323f

Could you check if this fixes the issue for you?

**Comment by BBrunekreeft** [comment]
This seems to have fixed the issues for me. Thanks!

**Comment by kabachello** [comment]
Working for me too! Thank you, @SilverFire !

**Comment by olstjos** [comment]
This is fixed, gracias amigos, merci les amis!

**Comment by Amadeco** [comment]
Same here, Thank you so very much @SilverFire !
